server:
  port: 8215   # 指定对应的端口号
  context-path: /SpringBootDay001   # 指定对应的项目名
  jsp-servlet:
    init-parameters:
      development: true   # 开启JSP的热部署
spring:
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource   #dbcp连接池
    driver-class-name: com.mysql.jdbc.Driver    #Mysql的驱动
    url: jdbc:mysql://localhost:3306/emsh?useUnicode=true&characterEncoding=UTF-8    #URL
    username: root
    password: root
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp            # 视图解析器
mybatis:
  type-aliases-package: com.baizhi.entity   #包中的类起别名
  mapper-locations: classpath:com/baizhi/dao/*Mapper.xml  #注册mapper文件